# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true

    python:
        code_rating: true
        duplicate_code: true

    ruby:
        code_rating: true
        duplicate_code: true

tools:
    external_code_coverage: true
        timeout: 600    # Timeout in seconds.

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover build/logs/clover.xml'
                coverage:
                    file: 'logs/clover.xml'
                    format: 'php-clover'