language: php

php:
  - 5.6
  - 5.5
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

# environment variable used in test suite
env: TEST_ENVIRONMENT=travis

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# install dependencies
install:
    - travis_retry composer self-update
    - travis_retry composer install --dev --no-interaction --prefer-source

# faster builds on new travis setup not using sudo
sudo: false

before_script:
    - "mysql -e 'create database `timefragment`;'"
    - php artisan migrate -n
    - php artisan dump-autoload

script:
    - mkdir -p build/logs
    - phpunit ./app/tests/ExampleTest.php

after_script:
  - php vendor/bin/coveralls -v